##  配置数据源
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/resume?useUnicode=true&characterEncoding=utf8
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: 123456
    #配置监控统计拦截的filters，去掉后监控 界面sql将无法统计，“wall”用于防火墙
    filters: stat,wall,log4j
    #最大活跃数
    maxActive: 20
    #初始化数量
    initialSize: 1
    #最大连接等待超时时间
    maxWait: 60000
    #打开PSCache,并且指定每个连接PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    #通过connectionProperties属性来打开mergeSql功能，慢SQL记录
    #connectionProperties: druid.stat.mergeSql = true;druid.stat.slowSqlMillis = 5000
    minldle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictabledleTimeMillis: 300000
    validationQuery: select 1 from dual
    testWhileldle: true
    testOnBorrow: false
    testOnReturn: false
  mvc:
    static-path-pattern: /**
  ## 模板引擎配置
  thymeleaf:
    mode: LEGACYHTML5
    encoding: utf-8
    servlet:
      content-type: text/html
    ## 热部署
    cache: false

server:
  port: 8080
  servlet:
    context-path: /resume
  address: localhost

##  Mybatis 配置
mybatis:
  mapper-locations: classpath:com.pany.resume.camp.mapper/*.xml
  type-aliases-package: com.pany.resume.camp.domain
